const Project=require('../models/Project');const Transaction=require('../models/Transaction');const Schedule=require('../models/Schedule');
const DEFAULT_CHECKLIST=['Brand confirmed','Shoot scheduled','Shoot completed','Content edited','Caption prepared','Client approval','Posted','Payment settled'];
const scheduleStatus=s=>s==='Completed'?'Completed':s==='Cancelled'?'Cancelled':'Planned';
const syncShoot=async(p)=>{const old=await Schedule.findOne({userId:p.userId,projectId:p._id,type:'Shoot'});if(!p.shootDate){if(old)await Schedule.deleteOne({_id:old._id});return;}const data={title:`${p.title} • Shoot`,type:'Shoot',date:p.shootDate,time:'',status:scheduleStatus(p.status),projectId:p._id,notes:p.notes||'',userId:p.userId};if(old)await Schedule.findByIdAndUpdate(old._id,data,{runValidators:true});else await Schedule.create(data)};
const normalizeChecklist=(items)=>Array.isArray(items)&&items.length?items.map(x=>({label:String(x.label||'').trim(),done:!!x.done})).filter(x=>x.label):DEFAULT_CHECKLIST.map(label=>({label,done:false}));
const syncPayments=async(p,uid)=>{if(p.promotionType!=='Paid'){for(const pay of p.payments||[]){if(pay.transactionId)await Transaction.deleteOne({_id:pay.transactionId,userId:uid});pay.transactionId=null;}p.payments=[];p.paymentReceived=false;p.paymentReceivedAt=undefined;p.paymentTransactionId=null;return;}
 if((p.payments||[]).length===0&&p.paymentReceived&&Number(p.agreedAmount||0)>0){p.payments=[{amount:Number(p.agreedAmount),status:'Paid',date:p.paymentReceivedAt||new Date(),method:'Other',notes:'Migrated from previous payment record.',transactionId:p.paymentTransactionId||null}];} let total=0;for(const pay of p.payments||[]){pay.amount=Number(pay.amount||0);pay.status=pay.status||'Paid';if(pay.amount<=0)continue;if(pay.status==='Paid')total+=pay.amount;let tx=pay.transactionId?await Transaction.findOne({_id:pay.transactionId,userId:uid}):null;const data={type:'income',title:`Payment • ${p.title}`,amount:pay.amount,category:'Paid Promotion',projectId:p._id,date:pay.date||new Date(),notes:pay.notes||`Payment via ${pay.method||'Other'}`,userId:uid};if(pay.status==='Paid'){if(tx){Object.assign(tx,data);await tx.save();}else{tx=await Transaction.create(data);pay.transactionId=tx._id;}}else if(tx){await Transaction.deleteOne({_id:tx._id,userId:uid});pay.transactionId=null;}}
 const due=Math.max(0,Number(p.agreedAmount||0)-total);p.paymentReceived=Number(p.agreedAmount||0)>0&&due<=0;p.paymentReceivedAt=p.paymentReceived?(p.payments||[]).slice().sort((a,b)=>new Date(b.date)-new Date(a.date))[0]?.date:undefined;p.paymentTransactionId=p.payments?.[0]?.transactionId||null;return {total,due};};
exports.list=async(req,res)=>{try{res.json(await Project.find({userId:req.user.id}).populate('clientId','name contactPerson phone instagram').sort({shootDate:1,createdAt:-1}));}catch(e){res.status(500).json({message:e.message});}};
exports.create=async(req,res)=>{try{const body={...req.body,userId:req.user.id,projectAddDate:req.body.projectAddDate||new Date(),agreedAmount:Number(req.body.agreedAmount||0),checklist:normalizeChecklist(req.body.checklist)};const p=await Project.create(body);await syncPayments(p,req.user.id);await p.save();await syncShoot(p);res.status(201).json(await Project.findById(p._id).populate('clientId','name contactPerson phone instagram'));}catch(e){res.status(400).json({message:e.message});}};
exports.update=async(req,res)=>{try{const p=await Project.findOne({_id:req.params.id,userId:req.user.id});if(!p)return res.status(404).json({message:'Project not found'});const body={...req.body};if(body.agreedAmount!==undefined)body.agreedAmount=Number(body.agreedAmount||0);if(body.checklist!==undefined)body.checklist=normalizeChecklist(body.checklist);Object.assign(p,body);if(!p.checklist?.length)p.checklist=normalizeChecklist();await syncPayments(p,req.user.id);await p.save();await syncShoot(p);res.json(await Project.findById(p._id).populate('clientId','name contactPerson phone instagram'));}catch(e){res.status(400).json({message:e.message});}};
exports.remove=async(req,res)=>{try{const x=await Project.findOneAndDelete({_id:req.params.id,userId:req.user.id});if(!x)return res.status(404).json({message:'Project not found'});for(const pay of x.payments||[])if(pay.transactionId)await Transaction.deleteOne({_id:pay.transactionId,userId:req.user.id});if(x.paymentTransactionId)await Transaction.deleteOne({_id:x.paymentTransactionId,userId:req.user.id});await Transaction.updateMany({userId:req.user.id,projectId:x._id},{$set:{projectId:null}});await Schedule.deleteMany({userId:req.user.id,projectId:x._id});res.json({message:'Project deleted'});}catch(e){res.status(400).json({message:e.message});}};
exports.analytics=async(req,res)=>{try{const p=await Project.findOne({_id:req.params.id,userId:req.user.id}).populate('clientId','name');if(!p)return res.status(404).json({message:'Project not found'});const tx=await Transaction.find({userId:req.user.id,projectId:p._id}).sort({date:-1});const income=tx.filter(x=>x.type==='income').reduce((s,x)=>s+x.amount,0),expense=tx.filter(x=>x.type==='expense').reduce((s,x)=>s+x.amount,0),received=(p.payments||[]).reduce((s,x)=>s+Number(x.amount||0),0);res.json({project:p,transactions:tx,income,expense,profit:income-expense,paymentSummary:{agreed:Number(p.agreedAmount||0),received,due:Math.max(0,Number(p.agreedAmount||0)-received),status:p.agreedAmount>0?(received>=p.agreedAmount?'Paid':received>0?'Partial':'Pending'):'Not set'}});}catch(e){res.status(500).json({message:e.message});}};
