const Project=require('../models/Project');const Transaction=require('../models/Transaction');const Schedule=require('../models/Schedule');
const scheduleStatus=s=>s==='Completed'?'Completed':s==='Cancelled'?'Cancelled':'Planned';
const syncShoot=async(p)=>{if(!p.shootDate)return;const data={title:`${p.title} • Shoot`,type:'Shoot',date:p.shootDate,time:'',status:scheduleStatus(p.status),projectId:p._id,notes:p.notes||'',userId:p.userId};const old=await Schedule.findOne({userId:p.userId,projectId:p._id,type:'Shoot'});if(old)await Schedule.findByIdAndUpdate(old._id,data,{runValidators:true});else await Schedule.create(data)};
exports.list=async(req,res)=>{try{res.json(await Project.find({userId:req.user.id}).sort({shootDate:1,createdAt:-1}));}catch(e){res.status(500).json({message:e.message});}};
exports.create=async(req,res)=>{try{const body={...req.body,userId:req.user.id,projectAddDate:req.body.projectAddDate||new Date()};if(body.agreedAmount!==undefined)body.agreedAmount=Number(body.agreedAmount||0);const p=await Project.create(body);if(p.promotionType!=='Paid'&&p.paymentTransactionId){await Transaction.deleteOne({_id:p.paymentTransactionId,userId:req.user.id});p.paymentTransactionId=null;p.paymentReceived=false;await p.save();}
 if(p.promotionType==='Paid'&&p.paymentReceived&&p.agreedAmount>0){const tx=await Transaction.create({type:'income',title:`Payment • ${p.title}`,amount:p.agreedAmount,category:'Paid Promotion',projectId:p._id,date:p.paymentReceivedAt||new Date(),notes:'Automatically added when project payment was marked received.',userId:req.user.id});p.paymentTransactionId=tx._id;p.paymentReceivedAt=p.paymentReceivedAt||new Date();await p.save();}await syncShoot(p);res.status(201).json(p);}catch(e){res.status(400).json({message:e.message});}};
exports.update=async(req,res)=>{try{const p=await Project.findOne({_id:req.params.id,userId:req.user.id});if(!p)return res.status(404).json({message:'Project not found'});const body={...req.body};if(body.agreedAmount!==undefined)body.agreedAmount=Number(body.agreedAmount||0);Object.assign(p,body);if(p.paymentReceived&&!p.paymentReceivedAt)p.paymentReceivedAt=new Date();if(!p.paymentReceived)p.paymentReceivedAt=undefined;await p.save();
 if(p.promotionType==='Paid'&&p.paymentReceived&&p.agreedAmount>0){let tx=p.paymentTransactionId?await Transaction.findOne({_id:p.paymentTransactionId,userId:req.user.id}):null;if(!tx){tx=await Transaction.create({type:'income',title:`Payment • ${p.title}`,amount:p.agreedAmount,category:'Paid Promotion',projectId:p._id,date:p.paymentReceivedAt||new Date(),notes:'Automatically added when project payment was marked received.',userId:req.user.id});p.paymentTransactionId=tx._id;await p.save();}else if(tx.amount!==p.agreedAmount){tx.amount=p.agreedAmount;await tx.save();}}
 if(!p.paymentReceived&&p.paymentTransactionId){await Transaction.deleteOne({_id:p.paymentTransactionId,userId:req.user.id});p.paymentTransactionId=null;await p.save();}
 await syncShoot(p);res.json(p);}catch(e){res.status(400).json({message:e.message});}};
exports.remove=async(req,res)=>{try{const x=await Project.findOneAndDelete({_id:req.params.id,userId:req.user.id});if(!x)return res.status(404).json({message:'Project not found'});await Transaction.updateMany({userId:req.user.id,projectId:x._id},{$set:{projectId:null}});await Schedule.deleteMany({userId:req.user.id,projectId:x._id});res.json({message:'Project deleted'});}catch(e){res.status(400).json({message:e.message});}};
exports.analytics=async(req,res)=>{try{const p=await Project.findOne({_id:req.params.id,userId:req.user.id});if(!p)return res.status(404).json({message:'Project not found'});const tx=await Transaction.find({userId:req.user.id,projectId:p._id}).sort({date:-1});const income=tx.filter(x=>x.type==='income').reduce((s,x)=>s+x.amount,0),expense=tx.filter(x=>x.type==='expense').reduce((s,x)=>s+x.amount,0);res.json({project:p,transactions:tx,income,expense,profit:income-expense});}catch(e){res.status(500).json({message:e.message});}};
