const Transaction=require('../models/Transaction');
const Project=require('../models/Project');
const allowed=['type','title','amount','category','projectId','date','notes'];
const cleanBody=body=>{const out={};allowed.forEach(k=>{if(body[k]!==undefined)out[k]=body[k]});return out};
const verifyProject=async(projectId,uid)=>{if(!projectId)return null;const p=await Project.findOne({_id:projectId,userId:uid}).select('_id');if(!p)throw new Error('Project not found.');return p._id};
exports.list=async(req,res)=>{try{const f={userId:req.user.id};if(req.query.type&&req.query.type!=='All')f.type=req.query.type;if(req.query.category&&req.query.category!=='All')f.category=req.query.category;if(req.query.projectId&&req.query.projectId!=='All')f.projectId=req.query.projectId;if(req.query.from||req.query.to){f.date={};if(req.query.from)f.date.$gte=new Date(req.query.from);if(req.query.to)f.date.$lte=new Date(req.query.to+'T23:59:59');}res.json(await Transaction.find(f).populate('projectId','title').sort({date:-1,createdAt:-1}));}catch(e){res.status(500).json({message:e.message});}};
exports.create=async(req,res)=>{try{const body=cleanBody(req.body);body.userId=req.user.id;body.amount=Number(body.amount||0);body.projectId=await verifyProject(body.projectId,req.user.id);body.source='Manual';res.status(201).json(await (await Transaction.create(body)).populate('projectId','title'));}catch(e){res.status(400).json({message:e.message});}};
exports.update=async(req,res)=>{try{const current=await Transaction.findOne({_id:req.params.id,userId:req.user.id});if(!current)return res.status(404).json({message:'Transaction not found'});if(current.source==='Project Payment')return res.status(400).json({message:'Project payment transactions are managed from the project payment section.'});const body=cleanBody(req.body);if(body.amount!==undefined)body.amount=Number(body.amount||0);if(body.projectId!==undefined)body.projectId=await verifyProject(body.projectId,req.user.id);const x=await Transaction.findOneAndUpdate({_id:req.params.id,userId:req.user.id},body,{new:true,runValidators:true}).populate('projectId','title');res.json(x);}catch(e){res.status(400).json({message:e.message});}};
exports.remove=async(req,res)=>{const x=await Transaction.findOne({_id:req.params.id,userId:req.user.id});if(!x)return res.status(404).json({message:'Transaction not found'});if(x.source==='Project Payment')return res.status(400).json({message:'Project payment transactions are managed from the project payment section.'});await Transaction.deleteOne({_id:x._id});res.json({message:'Transaction deleted'});};
