import React,{useEffect,useMemo,useState}from'react';
import{useNavigate}from'react-router-dom';
import{FiFolder,FiBarChart2,FiEdit3,FiCalendar,FiDollarSign,FiClock,FiArrowUpRight,FiArrowDownLeft,FiPlus}from'react-icons/fi';
import Header from'../../components/Header';import{getTransactions}from'../../services/transactionService';import{getProjects}from'../../services/projectService';import{getSchedules}from'../../services/scheduleService';import{money,dateText}from'../../utils/format';
const todayKey=()=>new Date().toISOString().slice(0,10);
export default function Dashboard(){
 const nav=useNavigate(),[tx,setTx]=useState([]),[projects,setProjects]=useState([]),[schedules,setSchedules]=useState([]),[err,setErr]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{Promise.all([getTransactions(),getProjects(),getSchedules()]).then(([t,p,s])=>{setTx(t);setProjects(p);setSchedules(s)}).catch(e=>setErr(e.response?.data?.message||'Could not load dashboard data.')).finally(()=>setLoading(false))},[]);
 const income=tx.filter(x=>x.type==='income').reduce((s,x)=>s+Number(x.amount||0),0),expense=tx.filter(x=>x.type==='expense').reduce((s,x)=>s+Number(x.amount||0),0);
 const monthKey=new Date().toISOString().slice(0,7);const monthTx=tx.filter(x=>String(x.date).slice(0,7)===monthKey);const monthIncome=monthTx.filter(x=>x.type==='income').reduce((s,x)=>s+Number(x.amount||0),0);const monthExpense=monthTx.filter(x=>x.type==='expense').reduce((s,x)=>s+Number(x.amount||0),0);
 const todayTasks=useMemo(()=>schedules.filter(x=>x.status==='Planned'&&String(x.date).slice(0,10)===todayKey()).slice(0,5),[schedules]);
 const upcoming=useMemo(()=>{const now=new Date();const end=new Date();end.setDate(end.getDate()+7);return schedules.filter(x=>x.status==='Planned'&&new Date(x.date)>=new Date(now.toDateString())&&new Date(x.date)<=end).sort((a,b)=>new Date(a.date)-new Date(b.date)).slice(0,5)},[schedules]);
 const pending=projects.map(p=>{const received=(p.payments||[]).filter(x=>x.status==='Paid').reduce((s,x)=>s+Number(x.amount||0),0);const due=Math.max(0,Number(p.agreedAmount||0)-received);const pendingPayments=(p.payments||[]).filter(x=>x.status==='Pending');const overdue=pendingPayments.some(x=>x.dueDate&&new Date(x.dueDate)<new Date());return{...p,due,overdue}}).filter(p=>p.promotionType==='Paid'&&p.due>0).sort((a,b)=>b.due-a.due).slice(0,4);
 const active=projects.filter(p=>!['Completed','Cancelled'].includes(p.status)).slice(0,4);
 const greeting=new Date().getHours()<12?'Morning':new Date().getHours()<17?'Afternoon':'Evening';
 return <><Header title="Soru_Venumaa" subtitle="Create • Track • Grow" menu brand/><div className="welcome"><div><strong>Good {greeting} 👋</strong><span>Here is what needs your attention today.</span></div><button className="round-action" onClick={()=>nav('/projects?add=1')}><FiPlus/></button></div>{err&&<div className="error-box">{err}</div>}
  <div className="balance-card"><div className="label">Current Balance</div><div className="balance">{money(income-expense)}</div><div className="stats-row"><div className="stat"><strong>{money(income)}</strong><small>Total Income</small></div><div className="stat"><strong>{money(expense)}</strong><small>Total Expenses</small></div></div></div>
  <div className="quick-grid"><button className="quick" onClick={()=>nav('/projects?add=1')}><div className="quick-icon"><FiFolder/></div>New Project</button><button className="quick" onClick={()=>nav('/money?add=expense')}><div className="quick-icon"><FiDollarSign/></div>Add Expense</button><button className="quick" onClick={()=>nav('/ideas?add=1')}><div className="quick-icon"><FiEdit3/></div>New Idea</button><button className="quick" onClick={()=>nav('/reports')}><div className="quick-icon"><FiBarChart2/></div>Reports</button></div>
  <div className="section-head"><div><h2>Today</h2><span className="subtle">{todayTasks.length} task{todayTasks.length===1?'':'s'} planned</span></div><button className="link-btn" onClick={()=>nav('/schedule')}>Calendar</button></div>
  {loading?<div className="list-card empty"><span className="mini-spinner"/> Loading…</div>:todayTasks.length?todayTasks.map(x=><div className="list-card transaction" key={x._id} onClick={()=>x.projectId?._id&&nav(`/projects/${x.projectId._id}/edit`)}><div className="avatar-icon"><FiCalendar/></div><div className="tx-main"><div className="tx-title">{x.title}</div><div className="tx-sub">{x.type}{x.time?` • ${x.time}`:''}{x.projectId?.title?` • ${x.projectId.title}`:''}</div></div><span className="badge-soft ongoing">Today</span></div>):<div className="empty-soft"><FiCheckCirclePlaceholder/> No tasks scheduled for today.</div>}
  <div className="section-head"><div><h2>This month</h2><span className="subtle">Actual money movement</span></div><button className="link-btn" onClick={()=>nav('/reports')}>Details</button></div>
  <div className="summary-grid"><div className="summary-box"><small>Income</small><strong className="income">{money(monthIncome)}</strong></div><div className="summary-box"><small>Expenses</small><strong className="expense">{money(monthExpense)}</strong></div><div className="summary-box"><small>Profit</small><strong>{money(monthIncome-monthExpense)}</strong></div></div>
  <div className="section-head"><div><h2>Payments to collect</h2><span className="subtle">Receivables from paid projects</span></div><button className="link-btn" onClick={()=>nav('/projects')}>View</button></div>
  {pending.length?pending.map(p=><div className="list-card transaction" key={p._id} onClick={()=>nav(`/projects/${p._id}/edit`)}><div className={`avatar-icon ${p.overdue?'alert-icon':''}`}><FiDollarSign/></div><div className="tx-main"><div className="tx-title">{p.title}</div><div className="tx-sub">{p.clientId?.name||'No client'} • {p.overdue?'Payment overdue':'Payment pending'}</div></div><strong className="expense">{money(p.due)}</strong></div>):<div className="empty-soft">No outstanding project payments 🎉</div>}
  <div className="section-head"><div><h2>Upcoming</h2><span className="subtle">Next 7 days</span></div></div>
  {upcoming.length?upcoming.map(x=><div className="list-card transaction" key={x._id} onClick={()=>x.projectId?._id&&nav(`/projects/${x.projectId._id}/edit`)}><div className="avatar-icon"><FiClock/></div><div className="tx-main"><div className="tx-title">{x.title}</div><div className="tx-sub">{dateText(x.date)}{x.time?` • ${x.time}`:''} • {x.type}</div></div></div>):<div className="empty-soft">Nothing planned for the next 7 days.</div>}
  <div className="section-head"><div><h2>Active projects</h2><span className="subtle">{active.length} shown</span></div><button className="link-btn" onClick={()=>nav('/projects')}>All projects</button></div>
  {active.map(p=><div className="project-card glass" key={p._id} onClick={()=>nav(`/projects/${p._id}/edit`)}><div className="thumb initial-thumb">{p.title?.charAt(0).toUpperCase()}</div><div className="project-body"><div className="project-title">{p.title}</div><div className="project-desc">{p.clientId?.name||'No client'} • {p.promotionType}</div><span className="badge-soft ongoing">{p.status}</span></div></div>)}
  <div className="section-head"><div><h2>Recent transactions</h2><span className="subtle">Latest money movement</span></div><button className="link-btn" onClick={()=>nav('/money')}>View all</button></div>
  {tx.slice(0,5).map(x=><div className="list-card transaction" key={x._id}><div className="avatar-icon">{x.type==='income'?<FiArrowDownLeft/>:<FiArrowUpRight/>}</div><div className="tx-main"><div className="tx-title">{x.title}</div><div className="tx-sub">{x.projectId?.title||x.category||'General'} • {dateText(x.date)}</div></div><div className={`tx-amount ${x.type}`}>{x.type==='income'?'+':'-'} {money(x.amount)}</div></div>)}
 </>;
}
function FiCheckCirclePlaceholder(){return <span className="empty-check">✓</span>}
