import React,{useEffect,useMemo,useState}from'react';import Header from'../../components/Header';import{getReport}from'../../services/reportService';import{money}from'../../utils/format';import{FiChevronLeft,FiChevronRight,FiTrendingUp}from'react-icons/fi';
export default function Reports(){const[y,setY]=useState(new Date().getFullYear()),[r,setR]=useState(null),[err,setErr]=useState('');useEffect(()=>{setR(null);getReport(y).then(setR).catch(e=>setErr(e.response?.data?.message||'Could not load report.'))},[y]);const max=Math.max(...(r?.monthly||[]).flatMap(m=>[m.income,m.expense]),1);const projectTotal=useMemo(()=>r?.projectAnalytics?.reduce((s,p)=>s+p.income,0)||0,[r]);const projectExpense=useMemo(()=>r?.projectAnalytics?.reduce((s,p)=>s+p.expense,0)||0,[r]);return <><Header title="Reports" subtitle="Understand where your money comes from and goes"/>{err&&<div className="error-box">{err}</div>}<div className="report-toolbar"><button onClick={()=>setY(y-1)}><FiChevronLeft/></button><strong>{y}</strong><button onClick={()=>setY(y+1)}><FiChevronRight/></button></div>{!r?<div className="list-card empty"><span className="mini-spinner"/> Loading report…</div>:<>
 <div className="summary-grid report-summary"><div className="summary-box"><small>Total income</small><strong className="income">{money(r.totalIncome)}</strong></div><div className="summary-box"><small>Total expenses</small><strong className="expense">{money(r.totalExpense)}</strong></div><div className="summary-box"><small>Net profit</small><strong>{money(r.balance)}</strong></div></div>
 <div className="report-card"><div className="section-head"><div><h2>Monthly income & expenses</h2><span className="subtle">Clear month-by-month view</span></div></div><div className="chart"><div className="bars">{r.monthly.map((m,i)=><div className="bar-group" key={i}><div className="bar income-bar" title={`Income ${money(m.income)}`} style={{height:`${Math.max(4,m.income/max*90)}%`}}/><div className="bar expense-bar" title={`Expense ${money(m.expense)}`} style={{height:`${Math.max(4,m.expense/max*90)}%`}}/><small>{new Date(2000,i).toLocaleString('en',{month:'short'})}</small></div>)}</div></div><div className="legend"><span><i className="legend-income"/> Income</span><span><i className="legend-expense"/> Expenses</span></div></div>
 <div className="report-card"><div className="section-head"><div><h2>Monthly breakdown</h2><span className="subtle">Income, expenses and profit for every month</span></div></div><div className="table-wrap"><table className="report-table"><thead><tr><th>Month</th><th>Income</th><th>Expenses</th><th>Profit</th></tr></thead><tbody>{r.monthly.map((m,i)=><tr key={i}><td>{new Date(2000,i).toLocaleString('en',{month:'long'})}</td><td className="income">{money(m.income)}</td><td className="expense">{money(m.expense)}</td><td>{money(m.balance)}</td></tr>)}</tbody></table></div></div>
 <div className="report-card"><div className="section-head"><div><h2>Project income & expenses</h2><span className="subtle">Only transactions linked to a project</span></div></div><div className="project-report-total"><div><small>Project income</small><strong className="income">{money(projectTotal)}</strong></div><div><small>Project expenses</small><strong className="expense">{money(projectExpense)}</strong></div><div><small>Project profit</small><strong>{money(projectTotal-projectExpense)}</strong></div></div>{r.projectAnalytics.filter(p=>p.income||p.expense||p.agreed).length?r.projectAnalytics.filter(p=>p.income||p.expense||p.agreed).map(p=><div className="list-card transaction" key={p.id}><div className="avatar-icon">{p.title.slice(0,1)}</div><div className="tx-main"><div className="tx-title">{p.title}</div><div className="tx-sub">{p.client||'No client'} • {p.status}</div><div className="project-finance-line"><span>Income {money(p.income)}</span><span>Expense {money(p.expense)}</span></div></div><strong className={p.profit>=0?'income':'expense'}>{money(p.profit)}</strong></div>):<div className="empty-soft">No project-linked transactions in {y}.</div>}</div>
 <div className="report-card"><div className="section-head"><div><h2>Project payment position</h2><span className="subtle">Agreed, received and still receivable</span></div></div>{r.projectAnalytics.filter(p=>p.agreed>0).map(p=><div className="payment-report-row" key={p.id}><div><strong>{p.title}</strong><small>{p.client||'No client'}</small></div><div><span>Agreed <b>{money(p.agreed)}</b></span><span>Received <b className="income">{money(p.received)}</b></span><span>Due <b className={p.due?'expense':'income'}>{money(p.due)}</b></span></div></div>)}</div>
 <div className="section-head"><div><h2>Category summary</h2><span className="subtle">Where your money is classified</span></div></div><div className="summary-grid">{[...Object.entries(r.categories.income).map(([n,v])=>({n,v,t:'Income'})),...Object.entries(r.categories.expense).map(([n,v])=>({n,v,t:'Expense'}))].sort((a,b)=>b.v-a.v).slice(0,8).map(x=><div className="summary-box" key={x.t+x.n}><small>{x.t} • {x.n}</small><strong>{money(x.v)}</strong></div>)}</div>
 <div className="section-head"><div><h2>Project overview</h2></div></div><div className="summary-grid"><div className="summary-box"><small>Total projects</small><strong>{r.projects.total}</strong></div><div className="summary-box"><small>Active</small><strong>{r.projects.active}</strong></div><div className="summary-box"><small>Completed</small><strong>{r.projects.completed}</strong></div></div>
 <div className="report-note"><FiTrendingUp/><span>Reports use actual transactions. Paid project installments appear as income automatically; manual project expenses appear when you link them to a project.</span></div>
 </>}</>}
